FROM node:20-alpine
WORKDIR /app
COPY package*.json ./

# AJUSTE: Removi o --production para garantir que ferramentas de build/TS instalem
RUN npm install 

COPY . .
RUN npx prisma generate
EXPOSE 3001
CMD ["npm", "start"]